### ISSUE TITLE
No bounding boxes and count labels for videos

### ISSUE THREAD

**Issue by rohg007** [JasonLing95/Yolov4-with-class-count#1]
Hi, I tried the given code for video but I'm only getting bounding boxes and labels for the first frame. There's no error as I'm getting Video Processing Complete! in the end. I'm attaching a sample output for reference.

![Web capture_2-2-2021_2436_colab research google com](https://user-images.githubusercontent.com/32675945/106519034-b4a43d80-6500-11eb-953e-22060863c7b7.jpeg)

**Comment by JasonHarambe** [comment]
the processed video is result.avi in the image. Clearly it is counting the variables (cars, persons, bus, handbag, backpack, trucks) in the video.

**Comment by rohg007** [comment]
But it only does that for the first frame of the video. It is not counting the variables for subsequent frames. Hence, I'm not getting bounding boxes and variables for frames other than the first one.

**Comment by JasonHarambe** [comment]
could you show me what command you ran and any raised error?

**Comment by rohg007** [comment]
!python detectvideo.py --weights ./checkpoints/yolov4-416 --size 416 --model yolov4 --video /content/drive/MyDrive/StreetScoring/UAV/datasets/videos/bangkok.mp4 --output /content/result.avi --count

This is the command I ran. 
No error is raised in the process and I'm getting "Video Processing Complete" message in the end.

**Comment by JasonHarambe** [comment]
option one could be to try with an avi format video. option two will be to retrain the yolo model to recognise whatever object you're trying to detect
